### ISSUE TITLE
Skip acceptance test in forks

### ISSUE THREAD

**Issue by rling-equinix** [equinix/terraform-provider-equinix#102]
When pushing to my forked branch where secrets are not defined, the acceptance tests should be skipped.

**Comment by ocobleseqx** [comment]
I found there are some [conversations](https://github.com/github/feedback/discussions/9098) around but it seems it is not possible to ignore forks yet. Alternatively, you can disable actions in your forked repository or create a:

Settings > Actions > General > Actions permissions > Disable Actions

You can also add a tag in your commits to skip actions 

https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
