### ISSUE TITLE
Some Metal CI/CD tests are failing on legacy slug use

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-equinix#130]
The use of older Equinix Metal device plan slugs and facility slugs have started causing CI failures as these plans and locations are phased out and the testing account has lost access to these resources.

Update Equinix Metal Facility and Device plan codes to modern codes:
* Legacy plans include: s1.large.x86, t1.small.x86
* Legacy facility codes include: dfw1, sjc1, ewr1

**Comment by ocobles** [comment]
I think this issue can be closed, with data plans and the fixes introduced by @ctreatma we saw all the tests green
