### ISSUE TITLE
Docs: categorized resources

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-equinix#182]
Similar to equinix/terraform-provider-equinix#183 

Comparing again to the AWS or GCP providers, the left-hand nav sections resources into different categories.  

The EM provider does not use categories today. https://registry.terraform.io/providers/equinix/metal/latest/docs

As the number of resources grows, we may find these beneficial.

For the EM provider, these categories could align with what is shown in the Portal: Servers, IPs & Networks, Storage, Projects, and the user profile menu (Profile, Keys, Organizations, Teams, Billing).

**Comment by ocobleseqx** [comment]
All resources were categorized in https://github.com/equinix/terraform-provider-equinix/releases/tag/v1.5.0. Similar to those mentioned cloud providers, here the categories represent the main service and not other low-level groups, in this case:

- Equinix Metal
- Equinix Fabric
- Equinix Metal
