### ISSUE TITLE
Facilities can be specified by ID, but then resources are destroyed and recreated after the provider normalizes to names

### ISSUE THREAD

**Issue by grahamc** [equinix/terraform-provider-equinix#202]
I wish I had a good log of this happening, but I created a spot market request in the facility `c9dcbd06-6797-4096-b648-1be16dd5d833` (`dfw2`) and it worked correctly. I then applied again, and the plan included destroying all my spot market requests, and recreating them, because the provider recorded the actual facility as `dfw2`. Maybe a reasonable option here is rejecting UUID-based facilities?

**Comment by displague** [comment]
Closing this since it relates to a deprecated feature #312
