### ISSUE TITLE
Allow query for all servers deployed at once

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [equinix/terraform-provider-equinix#211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

This originated from https://github.com/pulumi/pulumi-equinix-metal/issues/56 but the summary is a data source to provide an array (or similar) of all devices in a project, without having to individually query for each one (and have to have some way to identify each server to be queried.)

### New or Affected Resource(s)

equinix_project_devices

### Potential Terraform Configuration

Not providing this, as this is really for use in a downstream project.

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://github.com/pulumi/pulumi-equinix-metal/issues/56

**Comment by displague** [comment]
This was addressed in https://github.com/equinix/terraform-provider-equinix/pull/366

https://registry.terraform.io/providers/equinix/equinix/latest/docs/data-sources/equinix_metal_devices
