### ISSUE TITLE
Network Edge Device L2 Connection: Context Deadline Exceeded

### ISSUE THREAD

**Issue by pfeiffermj** [equinix/terraform-provider-equinix#23]
First and foremost, really great job on this provider! It is extremely useful!

**Reported Issue**: 

The equinix_ecx_l2_connection resource makes the appropriate REST calls to the Network Edge API and provisions the GCP Partner Interconnects with the supplied parameters. However, the Terraform process is terminated with by the error message shown below.

**Error Message**: 

```shell
module.network_edge.equinix_ecx_l2_connection.l2-cross-connect[1]: Creating...
module.network_edge.equinix_ecx_l2_connection.l2-cross-connect[0]: Creating...

Error: Equinix rest error: httpCode: 0, message: operation failed: Post "https://api.equinix.com/ne/v1/l2/connections": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

  on equinix/main.tf line 1, in resource "equinix_ecx_l2_connection" "l2-cross-connect":
   1: resource "equinix_ecx_l2_connection" "l2-cross-connect" {


Error: Equinix rest error: httpCode: 0, message: operation failed: Post "https://api.equinix.com/ne/v1/l2/connections": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

  on equinix/main.tf line 1, in resource "equinix_ecx_l2_connection" "l2-cross-connect":
   1: resource "equinix_ecx_l2_connection" "l2-cross-connect" {
```

**Resource settings**:

```shell
resource "equinix_ecx_l2_connection" "l2-cross-connect" {
  count   = length(var.region_list)
  name    = "gcp-dev-${element(var.region_list, count.index)}"
  profile_uuid        = "bd4570e2-d792-4a00-87f5-3bde040cdcd7" // GCP Partner Interconnect Zone 1
  device_uuid         = "${element(var.device_uuids, count.index)}"
  device_interface_id = var.device_interface
  speed               = var.speed
  speed_unit          = var.speed_unit
  notifications       = var.email_list
  seller_metro_code   = "${element(var.seller_metro_codes, count.index)}"
  seller_region       = "${element(var.region_list, count.index)}"
  authorization_key   = "${element(var.pairing_keys, count.index)}"
}
```

**Observations**:

It appears state is not being saved. I attempted a 2nd apply to receive an error message about the port already being in use, which I would expect. When I check the state file there is only this entry with no other information:

```shell
{
      "module": "module.network_edge",
      "mode": "managed",
      "type": "equinix_ecx_l2_connection",
      "name": "l2-cross-connect",
      "each": "list",
      "provider": "provider.equinix",
      "instances": []
}
```

Without state, the Equinix connections I made are absent from **terraform destroy**. 

Let me know if you have any questions. Thanks!

**Comment by mikouaj** [comment]
@pfeiffermj issue is caused by ECX Fabric APIs that sometimes require more time to produce response. This might be also related to general network latency.
Default timeout in our Terraform provider is set to 5 seconds.

### Workaround

Please manually increase timeout in provider configuration by setting `request_timeout` argument.

Example:
```
provider equinix {
  client_id         = var.equinix_client_id
  client_secret     = var.equinix_client_secret
  request_timeout   = 60
}
```

### Solution

We are performing analysis of API response times and will increase default timeout in our Terraform Provider accordingly.

**Comment by pfeiffermj** [comment]
That resolves the issue. Thank you @mikouaj !
