### ISSUE TITLE
Update terraform docs for "equinix/metal" 

### ISSUE THREAD

**Issue by jackgray** [equinix/terraform-provider-equinix#241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

There does not seem to be a guide for the new equinix/equinix provider for simple metal machine provisioning with Terraform. This document shows how to modify an existing provision https://registry.terraform.io/providers/equinix/equinix/latest/docs/guides/migration_guide_equinix_metal, however there is no complete example on how to deploy from scratch the new way using terriform.

### New or Affected Resource(s)

* equinix_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by displague** [comment]
@jackgray Equinix Metal Device creation examples are captured in the resource specific documentation: https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_metal_device#example-usage

Could you clarify what type of detail you would like to see added and where you would expect to find that?

**Comment by displague** [comment]
Google recently sent me to the metal/device docs and I think I felt your pain. One thing that I found helpful was that we link to the new resource documentation from the old resource documentation: https://registry.terraform.io/providers/equinix/metal/latest/docs/resources/device

**Comment by displague** [comment]
@jackgray I'm going to preemptively close this to reflect work done in the milestone.  

Let us know if there is anything you would like to see that is not included in the Metal device resource doc linked above.
