### ISSUE TITLE
equinix_metal_connection - cannot create shared connection after v1.5.0

### ISSUE THREAD

**Issue by dkaser** [equinix/terraform-provider-equinix#246]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/equinix/equinix v1.7.0

This also fails on version 1.6.0, 1.8.0, and 1.8.1... the only working version is 1.5.0.

### Affected Resource(s)

* equinix_metal_connection

### Terraform Configuration Files

```tf
resource "equinix_metal_connection" "fabric" {
  name            = "Equinix-Fabric"
  project_id      = data.equinix_metal_project.project.id
  metro           = local.metal_metro
  redundancy      = "redundant"
  type            = "shared"
  organization_id = "my-org-id"
  speed           = "1Gbps"
}
```

Note: speed isn't included in the sample code from the docs, but the provider requires it after v1.5.0.

### Debug Output

Without service_token_type: https://gist.github.com/dkaser/7a0c35a52dd3575e16e126c55f7c6762
With service_token_type: https://gist.github.com/dkaser/f65fb4a3917441d52c357e8581574dd5

### Expected Behavior

A shared interconnection should be created.

### Actual Behavior

An error is displayed indicating that service_token_type is required. Attempting to set service_token_type results in an unauthorized error.

### Steps to Reproduce

1. `terraform apply`

### References

* [Matching sample code in provider documentation](https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_metal_connection#shared-connection-for-organizations-without-connection-services-token-feature-enabled)

**Comment by ocobleseqx** [comment]
Hi @dkaser, thanks for bringing this up. I need to check wether it is just a Terraform issue or a limitation on the API
