### ISSUE TITLE
ECX L2 Get connection details by UUID Resource

### ISSUE THREAD

**Issue by pfeiffermj** [equinix/terraform-provider-equinix#26]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Right now the equinix_ecx_l2_connection resource provides the mechanism to POST a new L2 connection and the equinix_ecx_l2_connection_accepter resource provides the ability to PATCH the L2 connection. However, what is missing to have a full integration with AWS TF is a resource to GET connection details by UUID (/ecx/v3/l2/connections/{uuid}). 

The reason this is important is in the AWS I need to pass in the **connection_id** and **vlan** attributes to **resource "aws_dx_private_virtual_interface"** to create a private VIF. These values can be pulled from the GET operation mentioned above by **"key": "awsConnectionId"** and **"zSideVlanSTag"**. 

The net result of what is illustrated below is the DX can be fully provisioned between Equinix and AWS without any kind of manual intervention or having to write custom code to call the API to get the desired behavior.

### New or Affected Resource(s)

* (new) equinix_ecx_l2_connection_details

### Potential Terraform Configuration

```tf
resource "equinix_ecx_l2_connection" "connect" {
  count               = length(var.region_list)
  name                = format("%s%s", var.name_prefix, "${element(var.region_list, count.index)}")
  profile_uuid        = var.profile_uuid
  device_uuid         = "${element(var.device_uuids, count.index)}"
  device_interface_id = var.device_interface
  speed               = var.speed
  speed_unit          = var.speed_unit
  notifications       = var.email_list
  seller_metro_code   = "${element(var.seller_metro_codes, count.index)}"
  seller_region       = "${element(var.region_list, count.index)}"
  authorization_key   = "${element(var.pairing_keys, count.index)}"
}

resource "equinix_ecx_l2_connection_accepter" "accepter" {
  // creates dependency on equinix_ecx_l2_connection
  connection_id = equinix_ecx_l2_connection.connect.uuid 
  access_key = "YYY"
  secret_key = "XXX"
}

resource "equinix_ecx_l2_connection_details" "details" {
  connection_uuid        = equinix_ecx_l2_connection.connect.uuid
  // Waits until the connection is accepted to retrieve details 
  depends_on = [
    equinix_ecx_l2_connection_accepter.accepter
  ]
}

resource "aws_dx_private_virtual_interface" "private-vif" {
   // Rough idea of how you would have to parse the return data to get this key value
  connection_id     = 
  equinix_ecx_l2_connection_details.details.actionDetails.actionRequiredData.ELEMENT.awsConnectionId.value
  name              = "priv-vif"
  vlan              = equinix_ecx_l2_connection_details.details.zSideVlanSTag
  address_family    = "ipv4"
  bgp_asn           = 64999
  amazon_address    = "169.254.0.1/30"
  customer_address  = "169.254.0.2/30"
  bgp_auth_key      = var.bgp_password
  dx_gateway_id     = aws_dx_gateway.dx_gateway.id

}
```

### References

* #0000

**Comment by mikouaj** [comment]
@pfeiffermj thank you for feedback.
I believe that our provider is already producing all details needed for AWS interface resource:
* `zside_vlan_ctag` and `zside_vlan_stag` are both, argument that can be provided and attributes that may be computed by ECX FAbric on `equinix_ecx_l2_connection` resource
* `aws_connection_id` is an attribute that was recently added (issue #22) on `equinix_ecx_l2_connection_accepter` resource

Therefore, you interface configuration could look like:
```
resource "aws_dx_private_virtual_interface" "private-vif" {
  connection_id     = 
  equinix_ecx_l2_connection_accepter.accepter.aws_connection_id
  name              = "priv-vif"
  vlan              = equinix_ecx_l2_connection.connect.zside_vlan_stag
  address_family    = "ipv4"
  bgp_asn           = 64999
  amazon_address    = "169.254.0.1/30"
  customer_address  = "169.254.0.2/30"
  bgp_auth_key      = var.bgp_password
  dx_gateway_id     = aws_dx_gateway.dx_gateway.id
}
```

You can check whats in local state after ECXF connection and accepter creation with `terraform show`.

Please verify that above works for you on build from master branch.
I will walk through resource documentation to verify that it is accurate.

**Comment by pfeiffermj** [comment]
This seems to work as you described @mikouaj . I am hitting one snag, but I think it might be how I am accessing the output and not an issue with the provider. I should be able to finish testing sometime this week and can report back to let you know if I got this to work. Would you be okay holding this issue open for another couple of days? Thanks!

**Comment by pfeiffermj** [comment]
Hey @mikouaj . So it looks like this works as you described, but I am encountering a different but related issue.

The ** equinix_ecx_l2_connection_accepter** is returning the ** aws_connection_id** before it is fully provisioned in AWS.

Here is a snippet from my AWS Console:

ID: dxcon-fgmgi3yi 
Name: dev-us-east-2
Region: us-east-2
Location: Equinix CH2, Chicago, IL
Bandwidth: 50Mbps
State: pending

The TF does have an implied dependency and it is receiving the correct values in this resource:

```shell
resource "aws_dx_private_virtual_interface" "private-vif" {
  connection_id     = equinix_ecx_l2_connection_accepter.l2-accepter.aws_connection_id
  name              = "eqxtf-priv-vif"
  vlan              = equinix_ecx_l2_connection.l2-connection[0].zside_vlan_stag
  address_family    = "ipv4"
  bgp_asn           = 64999
  amazon_address    = "169.254.0.1/30"
  customer_address  = "169.254.0.2/30"
  bgp_auth_key      = var.bgp_password
  dx_gateway_id     = aws_dx_gateway.dx_gateway.id
}

$ terraform output
cloud_connection_id = dxcon-fgmgi3yi
cloud_connection_vlan = [
  381,
]

```

But since the DX is not in an **available** state it tries to create the VIF and results in the following error:

**Error: error creating Direct Connect private virtual interface: DirectConnectClientException: The specified Connection ID is not available**

I think I can workaround this issue with [time sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep), but was wondering if the **accepter** could be adjusted to wait until the status for both of these fields read **provisioned**? The snippet below is from the Exchange.

```shell
Status: Provisioned
Provider Status: Provisioned
```

Let me know what you think. Thanks!

**Comment by mikouaj** [comment]
Hey @pfeiffermj thanks again for feedback, indeed accepter should wait for the target "provisioned" state.
I will introduce the change shortly.

**Comment by mikouaj** [comment]
@pfeiffermj I've committed fix to master branch, accepter waits for connection's provider status to be provisioned.

**Comment by pfeiffermj** [comment]
Thanks @mikouaj !
