### ISSUE TITLE
Can we use overrides to fix tests that are driven by configs in `examples/`

### ISSUE THREAD

**Issue by ctreatma** [equinix/terraform-provider-equinix#277]
The tests for the new Fabric resources & data sources use the terraform configs in the `examples/` directory.  This is convenient because we can regularly validate that our examples still work, and we can avoid defining duplicate configurations in the tests themselves.  Problems arise when we introduce tests in this style that cover unreleased resources or data sources.  The `examples/` are intended for end-user consumption, so they pull down the latest official release of our provider, which means that the tests can't pass until the code they're testing has already been released to customers.

Terraform has a notion of override files that can be used to change parts of an existing configuration: https://developer.hashicorp.com/terraform/language/files/override

Can we update our tests to create an override file that uses a locally-built provider instead of downloading the latest publicly-available release?

**Comment by ctreatma** [comment]
Note: the Fabric tests are using `terratest`, so we'll have to dig into how `terratest` works to see if/where we can inject override files into the configuration under test.

https://terratest.gruntwork.io/docs/

**Comment by displague** [comment]
@ctreatma can this be closed now that #684 was merged?

**Comment by ctreatma** [comment]
Yep, this is irrelevant now.  The newer Fabric acceptance tests are not terratest-based, and terratest has been torn out of this repo.
