### ISSUE TITLE
AuthenticationKey in Resource Network BGP schema should be Optional instead of Required

### ISSUE THREAD

**Issue by ocobleseqx** [equinix/terraform-provider-equinix#28]
AuthenticationKey is defined [here ](https://github.com/equinix/terraform-provider-equinix/blob/fa84902161955e43fa3278bba5f6a6e14af88992/equinix/resource_network_bgp.go#L77) as required, but in some cases (Google Cloud for example) it is not possible to add an authentication key when you configure the BGP session so it should be optional or accept empty strings.

**Comment by mikouaj** [comment]
@ocobleseqx thanks for pointing that out.
Network Edge API requires BGP secret to be provided, but I will test with an empty string.
From schema point of view Optional is most elegant solution :)
