### ISSUE TITLE
Update tests/docs/etc. to account for decommissioned data centers

### ISSUE THREAD

**Issue by ctreatma** [equinix/terraform-provider-equinix#281]
A few data centers are no longer supported.  We have at least a couple acceptance tests that are using these data centers, which causes those tests to fail.  We may also be referencing those data centers in examples or guides.  Update any tests/examples/guides to replace references to unsupported data centers as follows:

- NRT1 => TY
- AMS1 => AM
- SJC1 => SV
- DFW2 => DA
- EWR1 => NY

**Comment by displague** [comment]
Dupe of #130
