### ISSUE TITLE
GPG signature error when using terraform provider

### ISSUE THREAD

**Issue by stephenmass-ftdr** [equinix/terraform-provider-equinix#30]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
```
bash-5.0# terraform -version
Terraform v0.12.13
+ provider.aws v3.11.0
+ provider.google v3.44.0
+ provider.google-beta v3.44.0
+ provider.random v3.0.0
```

### Affected Resource(s)

* equinix_XXXXX

### Terraform Configuration Files

I'm just trying to initialize a blank terraform configuration to ensure authentication is working with the equinix provider. 
```tf
provider "equinix/equinix" {
}
```

I have my client ID and client secret exported as environment variables according to the provider documentation.

```
bash-5.0# env
...
PWD=/proj/terraform/gcp/environment
EQUINIX_API_CLIENTSECRET=<redacted>
HOME=/root
TERM=xterm
EQUINIX_API_CLIENTID=<redacted>
...
```
### Debug Output
```
bash-5.0# terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Error verifying GPG signature for provider "equinix/equinix"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.


Error: unable to verify signature

```

### Expected Behavior

Terraform initializes all providers successfully.

### Actual Behavior

```
Error verifying GPG signature for provider "equinix/equinix"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.
```
### Steps to Reproduce

1. `terraform init`

**Comment by mikouaj** [comment]
@stephenmass-ftdr thanks for bringing that up.
Seems that issue is related with TF version < 13, I'm looking into that.

**Comment by paultyng** [comment]
The new namespacing only works in Terraform >= 0.13, you can possibly get this to work by using `-verify-plugins=false` but you are in unsupported territory here.

**Comment by mikouaj** [comment]
Terraform 12 fetches release from correct Github repo but fails on checksum file signature verification. It expects it to be signed by Hashicorp key. File is signed with Equinix key that is added to Terraform registry instead (what works well for Terraform >13).

```
2020/11/18 15:08:37 [ERROR] error verifying signature against HashiCorp public key: openpgp: signature made by unknown entity
```



Full debug log: https://gist.github.com/mikouaj/10bd3341c7b454c17058fb2f3610d576

I've reached out to Hashicorp guys to see if anything can be done with that.

**Comment by mikouaj** [comment]
Issue has been resolved by Hashicorp Registry team - they have published it under  https://releases.hashicorp.com/terraform-provider-equinix/ 

```
 % cat main.tf
provider "equinix" {}
 % ./terraform version
Terraform v0.12.29
 % ./terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "equinix" (terraform-providers/equinix) 1.0.2...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.equinix: version = "~> 1.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
 %
```

**Comment by stephenmass-ftdr** [comment]
Wonderful! Thanks so much for assisting with this!
