### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by ocobles** [equinix/terraform-provider-equinix#309]
https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_metal_connection

Replace (or add) `a_side` and `z_side` references with `Metal-billed` and `Fabric-billed` to stay aligned with the documentation 

https://deploy.equinix.com/developers/docs/metal/interconnections/introduction/#fabric-virtual-connections-metal-billed

I also realized that some links are broken

[Equinix Fabric - software-defined interconnections](https://metal.equinix.com/developers/docs/networking/fabric/)

Edit: I think that GA warning Note can be deleted, @displague ?

**Comment by ocobleseqx** [comment]
Other findings:
- Update https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_metal_organization#example-usage to add required `address` field
