### ISSUE TITLE
Add possible values for equinix_ecx_l2_sellerprofile name property

### ISSUE THREAD

**Issue by mxdlx** [equinix/terraform-provider-equinix#34]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

I'm about to setup a GCP interconnect so I'm checking your provider. I encountered the sellerprofile data source and got curious about the possible values for the name property so I found [this Equinix youtube tutorial](https://www.youtube.com/watch?v=R9EgD0N89aA) that shows two zones for the interconnect. That's valuable information for the resource page, assuming that value is restricted to either "Google Cloud Partner Interconnect Zone 1" or "Google Cloud Partner Interconnect Zone 2".

### New or Affected Resource(s)

* equinix_ecx_l2_sellerprofile

### Potential Terraform Configuration

```tf
data "equinix_ecx_l2_sellerprofile" "gcpi-1" {
  name = "Google Cloud Partner Interconnect Zone 2"
}
```

**Comment by mikouaj** [comment]
@mxdlx thanks for rising that up. Although there is vast amount of sellers available on Equinix Fabric, I agree that we can list most popular ones (i.e. CSPs) in data source documentation.

Other solution that we have considered is to provide data source returning multiple results, for further filtering.

**Comment by mxdlx** [comment]
It was my first time doing the interconnect (or any kind of DC to the Cloud connection). I think it's a process that deserves one of those tech blog posts for the little details since the provider works.

**Comment by mikouaj** [comment]
@mxdlx we plan to create tech blog posts and video material for different Terraform use cases in near future :-)

**Comment by eugeniy** [comment]
Could be helpful to provide a way to pull a list of those from the API as well: https://developer.equinix.com/docs/ecx-layer-2-buyer-apis-v3#get-layer-2-service-profiles-services

**Comment by mikouaj** [comment]
@eugeniy we can achieve that by providing plural version of `equinix_ecx_l2_sellerprofile` data source that will return list of profiles instead of a single profile.
From our, Equinix point of view, that is preferred way as we avoid documenting profile names that are managed by service providers and not Equinix. On the other hand I understand need of providing clear filtering criteria for such list.
We are discussing about that internally and will propose some solution soon.

**Comment by ocobleseqx** [comment]
This issue is deprecated and a datasource currently exists to list/filter seller profiles based on metro/organization/name_regex ... https://registry.terraform.io/providers/equinix/equinix/latest/docs/data-sources/equinix_ecx_l2_sellerprofiles
