### ISSUE TITLE
Run Fabric resource tests in CI

### ISSUE THREAD

**Issue by ctreatma** [equinix/terraform-provider-equinix#344]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently, CI only runs acceptance tests for Metal resources & data sources.  This means that changes to Fabric resources don't go through any kind of automated validation.  To build confidence in Pull Requests that update Fabric resources, we should update our GitHub Actions workflows to run the Fabric tests automatically in addition to the Metal tests.

- Fabric tests should run in a separate workflow from Metal tests
- The Fabric test workflow should run terraform acceptance tests as well as terragrunt end-to-end tests in the `tests/` directory

### New or Affected Resource(s)

* equinix_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by displague** [comment]
When we have Fabric CI, do we need GHA patterns that allow these E2E tests to run in parallel to Metal E2E tests?
