### ISSUE TITLE
Authorization key validation failed

### ISSUE THREAD

**Issue by mxdlx** [equinix/terraform-provider-equinix#36]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

0.13.5 (using terraform cloud)

### Affected Resource(s)

* equinix_ecx_l2_connection

### Terraform Configuration Files

```tf
resource "equinix_ecx_l2_connection" "XXXXX" {
  name              = "XXXX"
  profile_uuid      = data.equinix_ecx_l2_sellerprofile.test_profile.uuid
  speed             = 1
  speed_unit        = "GB"
  notifications     = ["ops@example.com"]
  port_uuid         = data.equinix_ecx_port.test_port.uuid
  vlan_stag         = 300
  seller_region     = google_compute_interconnect_attachment.test_attach.region
  #seller_metro_code = var.gcp_metro_code
  authorization_key = google_compute_interconnect_attachment.test_attach.pairing_key
}
```

### Debug Output

```
Equinix REST API error: Message: "Bad Request", HTTPCode: 400, ApplicationErrors: [Code: "IC-LAYER2-AUTH-004", Property: "authorization_key", Message: "Authorization Key Validation Failed", AdditionalInfo: "Pairing key must end with /2"]

on equinix.tf line 9, in resource "equinix_ecx_l2_connection" "XXXXX":
   9: resource "equinix_ecx_l2_connection" "XXXXX"
```

### Expected Behavior

The L2 connection should have been created.

### Actual Behavior

The example in this repository uses `authorization_key = google_compute_interconnect_attachment.test-1.pairing_key`. I got this error `Pairing key must end with /2` so I went and checked the created pairing key and it actually ends with `/us-central1/any`. I hope this is an actual bug.

### Steps to Reproduce

1. `terraform apply`

**Comment by mxdlx** [comment]
I found my issue here, I was using a bad value for the GCP VLAN attachmente. For `google_compute_interconnect_attachment` its `edge_availability_domain` must be set to `availability-domain-2` to pass the "Pairing key must end with /2".

**Comment by mikouaj** [comment]
@mxdlx glad to read that you have solved your issue.
Indeed, for GCP Partner Interconnect, Equinix Fabric requires paring keys from VLAN attachments within selected zone (also called edge availability domain). Therefore, you have to specify `edge_availability_domain` argument in GCP VLAN attachment. 

This zone / edge availability domain has to match GCP's Service Profile used for a given connection:
* `Google Cloud Partner Interconnect Zone 1` service profile corresponds to `availability-domain-1`
* `Google Cloud Partner Interconnect Zone 2` service profile corresponds to `availability-domain-2`
