### ISSUE TITLE
Migrate to terraform plugin framework

### ISSUE THREAD

**Issue by ctreatma** [equinix/terraform-provider-equinix#365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Our Terraform provider is currently based on terraform-plugin-sdk which is no longer prioritized by Hashicorp and may not receive new features going forward.

The new hotness is the terraform plugin framework, which is getting the bulk of Hashicorp’s attention and has some useful things like built-in attribute validation so we can, for example, validate that strings are a certain length or match a regex without writing our own validation functions.

There is a migration guide here: https://developer.hashicorp.com/terraform/plugin/framework/migrating 

Given the number of resources we have, we may want to use muxing (documented in the link above) to gradually convert the provider.  Testing will be an issue because (1) Metal tests can be flaky and (2) Fabric and NE tests don’t exist (or at least, not in a way that we can run them ourselves on demand).

**Comment by displague** [comment]
I think we need to do #106 as a requirement of this work because sub-directory packages are part of Framework's best-practices. If Framework can be introduced without moving the resources to separate directories, this is not a concern.

Example of the cyclic dependencies that we'll encounter if we don't move helpers first:
- internal/services/metal/devices/resource.go import /equinix to get SomeHelper
- equinix/provider.go import internal/services/metal/devices to get device.Resource

**Comment by ocobles** [comment]
I have created an [issue](https://github.com/equinix/terraform-provider-equinix/issues/612) to track the migrated resources, can we close this one?

**Comment by ctreatma** [comment]
As originally written, this issue has been completed: we've introduced muxing to support gradual migration of SDKv2 resources to the terraform-plugin-framework provider and have migrated a few resources to that provider.  The process of migrating the remaining resources out of SDKv2 is captured in the issue Oscar linked above.
