### ISSUE TITLE
Fabric layer2 connection accepter should wait for available connectionState in AWS

### ISSUE THREAD

**Issue by mikouaj** [equinix/terraform-provider-equinix#37]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Creation of `equinix_ecx_l2_connection_accepter` does not reflect `connectionState` of a connection on AWS side. In most cases, after successful creation of accepter resource `connectionState` will be `pending`, as it takes up to few minutes to fully initialize the connection. This prevents creation of AWS Direct Connect private / public / transit interfaces using given connection.

Solution for that is to make creation of `equinix_ecx_l2_connection_accepter` waiting for `connectionState` to be `available`. This check can be achieved by using AWS `DescribeConnections` API.

### New or Affected Resource(s)

* `equinix_ecx_l2_connection_accepter`

### Potential Terraform Configuration

```tf
resource "equinix_ecx_l2_connection_accepter" "tst-dot1q" {
  connection_id = equinix_ecx_l2_connection.test.id
  access_key    = var.aws_access_key
  secret_key    = var.aws_secret_key
}

# creation of below will fail as connection with a provided ID
# will not be available yet
resource "aws_dx_private_virtual_interface" "example" {
  connection_id    = equinix_ecx_l2_connection_accepter.test.aws_connection_id
  name             = "test"
  vlan             = 1404
  address_family   = "ipv4"
  bgp_asn          = 50001
  amazon_address   = "10.0.0.2/30"
  customer_address = "10.0.0.1/30"
  bgp_auth_key     = "secret"
  vpn_gateway_id   = aws_vpn_gateway.example.id
}
```

### References

N/A

**Comment by sliuuu** [comment]
when will this be fixed, we did a customer demo recently and keep getting Error: error creating Direct Connect private virtual interface: DirectConnectClientException: The specified Connection ID is not available...

**Comment by mikouaj** [comment]
@sliuuu we are working on it.
As for now, please use workaround and manually delay creation of `aws_dx_private_virtual_interface`. It will give time to AWS to fully provision connection.
This can be done by using `time_sleep` resource, as [described here](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep).

Example:
*(introduces 120s delay)*
```
resource "equinix_ecx_l2_connection_accepter" "test" {
  connection_id = equinix_ecx_l2_connection.test.id
  access_key    = var.aws_access_key
  secret_key    = var.aws_secret_key
}

resource "time_sleep" "test-accepter-wait" {
  depends_on = [equinix_ecx_l2_connection_accepter.test]
  create_duration = "120s"
}

resource "aws_dx_private_virtual_interface" "example" {
  depends_on = [time_sleep.test-accepter-wait]
  connection_id    = equinix_ecx_l2_connection_accepter.test.aws_connection_id
  name             = "test"
  vlan             = 1404
  address_family   = "ipv4"
  bgp_asn          = 50001
  amazon_address   = "10.0.0.2/30"
  customer_address = "10.0.0.1/30"
  bgp_auth_key     = "secret"
  vpn_gateway_id   = aws_vpn_gateway.example.id
}
```

**Comment by mikouaj** [comment]
More analysis showed that using AWS APIs may be not required. 

Equinix Fabric's L2 connection has `providerStatus` attribute that, in AWS case, should correspond to Hosted Direct Connect connection state.
If `providerStatus` reported by the Fabric is `PROVISIONED`, then connection state on AWS side should be `Available`. Unfortunately, small bug in accepter's create wait logic caused testing of wrong state. It was fixed now.

@sliuuu please check solution in latest version of Terraform Equinix Provider (v1.0.4) and let us know if that works for you.

**Comment by sliuuu** [comment]
@mikouaj 
Ran the code without the AWS APIs

aws_dx_private_virtual_interface.example: Creating...

Error: error creating Direct Connect private virtual interface: DirectConnectClientException: The specified Connection ID is not available

changed provider to block to 
terraform {
  required_providers {
    equinix = {
      source  = "equinix/equinix"
      version = "=1.0.4"
    }
  }
}

terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding equinix/equinix versions matching "1.0.4"...
- Finding latest version of hashicorp/aws...
- Installing equinix/equinix v1.0.4...
- Installed equinix/equinix v1.0.4 (signed by a HashiCorp partner, key ID 1A65631C7288685E)
- Installing hashicorp/aws v3.22.0...
- Installed hashicorp/aws v3.22.0 (signed by HashiCorp)

aws_dx_private_virtual_interface.example: Still creating... [5m0s elapsed]
aws_dx_private_virtual_interface.example: Creation complete after 5m0s [id=dxvif-xxxxxxxxx]

All good now! thanks!
