### ISSUE TITLE
Support additional authentication methods for accepting AWS direct connect requests

### ISSUE THREAD

**Issue by eugeniy** [equinix/terraform-provider-equinix#38]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Creating an AWS connection, requires acceptance of the connection on the AWS side. Currently, the accepter resource only support static credentials, which can result in them being exposed (see [a relevant AWS provider section](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#static-credentials)).

AWS terraform provider (and SDK) have several ways to authenticate, some of those should be supported here as well.

### New or Affected Resource(s)

* ecx_l2_connection_accepter

### Potential Terraform Configuration

Environment variables:
```
$ export AWS_ACCESS_KEY_ID="anaccesskey"
$ export AWS_SECRET_ACCESS_KEY="asecretkey"
$ export AWS_DEFAULT_REGION="us-west-2"

resource "equinix_ecx_l2_connection_accepter" "accepter" {
  connection_id = equinix_ecx_l2_connection.awsConn.id
}
```

AWS profile (by default `$HOME/.aws/credentials`):
```
resource "equinix_ecx_l2_connection_accepter" "accepter" {
  connection_id = equinix_ecx_l2_connection.awsConn.id
  profile       = "customprofile"
}
```

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs

**Comment by mikouaj** [comment]
@eugeniy thanks for proposing this significant enhancement!
I've added possibility to use both env variables and shared configuration files.
Code is already in master branch.
