### ISSUE TITLE
Secondary device always forces recreate on update

### ISSUE THREAD

**Issue by eugeniy** [equinix/terraform-provider-equinix#39]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v0.13.5

### Affected Resource(s)

* equinix_ecx_l2_connection

### Terraform Configuration Files

```tf

data "equinix_ecx_l2_sellerprofile" "aws_dc_hc" {
  name                     = "AWS Direct Connect - High Capacity"
  organization_global_name = "AWS"
}

resource "equinix_ecx_l2_connection" "aws_connection" {
  name = var.connection_name

  device_uuid = equinix_network_device.us_east_ha.uuid

  notifications = var.ecx_notifications

  profile_uuid = data.equinix_ecx_l2_sellerprofile.aws_dc_hc.id

  speed             = 5
  speed_unit        = "GB"
  seller_metro_code = "DC"
  seller_region     = "us-east-1"

  authorization_key = data.aws_caller_identity.current.account_id

  secondary_connection {
    name        = var.secondary_connection_name
    device_uuid = equinix_network_device.us_east_ha.redundant_id
  }
}
```

### Expected Behavior

After primary and secondary connections are successfully created, running terraform again without any changes should not recreate those connections.

### Actual Behavior

Running terraform again without making any changes, forces recreation of both connections.
This only happens when the `secondary_connection` is defined.

```
  # equinix_ecx_l2_connection.aws_connection must be replaced
-/+ resource "equinix_ecx_l2_connection" "aws_connection" {
      ...
      ~ provider_status   = "PENDING_APPROVAL" -> (known after apply)
      ~ redundancy_type   = "primary" -> (known after apply)
      ~ redundant_uuid    = "97cc950d-<redacted>-060a51ee56b1" -> (known after apply)
        seller_metro_code = "DC"
        seller_region     = "us-east-1"
        speed             = 5
        speed_unit        = "GB"
      ~ status            = "PROVISIONED" -> (known after apply)
      ~ uuid              = "1a441fe7-<redacted>-0df6f009b4af" -> (known after apply)
      ...

      - secondary_connection { # forces replacement
          - device_interface_id = 0 -> null
          - device_uuid         = "e9cb259a-<redacted>-98e9fd0c037d" -> null
          - name                = "aws_equinix_test" -> null
          - provider_status     = "PROVISIONED" -> null
          - redundancy_type     = "secondary" -> null
          - redundant_uuid      = "1a441fe7-<redacted>-0df6f009b4af" -> null
          - status              = "PROVISIONED" -> null
          - uuid                = "97cc950d-<redacted>-060a51ee56b1" -> null
          - vlan_ctag           = 0 -> null
          - vlan_stag           = 5875 -> null
          - zside_port_uuid     = "<redacted>" -> null
          - zside_vlan_ctag     = 0 -> null
          - zside_vlan_stag     = 311 -> null
        }
      + secondary_connection { # forces replacement
          + device_uuid     = "e9cb259a-<redacted>-98e9fd0c037d"
          + name            = "aws_equinix_test"
          + provider_status = (known after apply)
          + redundancy_type = (known after apply)
          + redundant_uuid  = (known after apply)
          + status          = (known after apply)
          + uuid            = (known after apply)
          + vlan_stag       = (known after apply)
          + zside_port_uuid = (known after apply)
          + zside_vlan_ctag = (known after apply)
          + zside_vlan_stag = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

### Steps to Reproduce

1.  Create a `equinix_ecx_l2_connection` for AWS, containing `secondary_connection` with `device_uuid`
2. `terraform apply`
3. `terraform apply`

### References

* #0000

**Comment by mikouaj** [comment]
Issue seems to be caused by secondary's connection `vlan_stag` that is assigned by Equinix Fabric automatically if not provided.  This makes `vlan_stag` within `secondary_connection` block as **both** Optional + Computed what is not working well in embeded `schema.TypeSet` with own resource schemas.

Workaround for this issue could be enforcing user to specify this tag, even with the device (after removing existing constraints). This is silly however, so I'm Investigating other solution for this issue.

**Comment by mikouaj** [comment]
Issue was solved after changing internal representation of `secondary_connection` from Set to List, what allows to use `Computed` + `Optional` schema settings on nested block. Such combo is no allowed with Set as remote changes on such attributes cause hash value change of entire element.
