### ISSUE TITLE
equinix_fabric_cloud_router resource and datasource don't have any subcategory defined

### ISSUE THREAD

**Issue by ocobles** [equinix/terraform-provider-equinix#393]
add subcatergory `Fabric`. I'm not sure if there is anything we can do to have tf-plugin-docs automatically define the subcategory

![image](https://github.com/equinix/terraform-provider-equinix/assets/68897552/b88e49bb-c8ca-4c9a-858c-5d13c1403b7a)

**Comment by thogarty** [comment]
This has been resolved in version 1.18.0 of the Terraform Provider: https://registry.terraform.io/providers/equinix/equinix/1.18.0/docs/data-sources/equinix_fabric_cloud_router

Issue closed.
