### ISSUE TITLE
Unable to find all seller profiles

### ISSUE THREAD

**Issue by eugeniy** [equinix/terraform-provider-equinix#41]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

0.13.5

### Affected Resource(s)

* equinix_ecx_l2_sellerprofile

### Terraform Configuration Files

```tf
data "equinix_ecx_l2_sellerprofile" "aws_dx" {
  name = "AWS Direct Connect - High Capacity"
}

data "equinix_ecx_l2_sellerprofile" "gcp_zone2" {
  name                     = "Google Cloud Partner Interconnect Zone 2"
  organization_global_name = "GOOGLE"
}
```

### Debug Output

Pulled out relevant sections. It appears there are multiple pages for seller profiles, 2 requests are sent to the API. There is only 1 response (for the second page) in the output.

```
Error: profile query returned no results, please change your search criteria



Error: profile query returned no results, please change your search criteria

...
2021-02-11T15:29:15.320-0800 [INFO]  plugin.terraform-provider-equinix: 2021/02/11 15:29:15 [DEBUG] Equinix API Request Details:
---[ REQUEST ]---------------------------------------
GET /ecx/v3/l2/serviceprofiles/services?pageNumber=1&pageSize=100 HTTP/1.1
Host: api.equinix.com
User-Agent: equinix/ecx-go
Accept: application/json
Accept-Encoding: gzip


-----------------------------------------------------: timestamp=2021-02-11T15:29:15.320-0800
2021-02-11T15:29:16.353-0800 [INFO]  plugin.terraform-provider-equinix: 2021/02/11 15:29:16 [DEBUG] Equinix API Request Details:
---[ REQUEST ]---------------------------------------
GET /ecx/v3/l2/serviceprofiles/services?pageNumber=2&pageSize=100 HTTP/1.1
Host: api.equinix.com
User-Agent: equinix/ecx-go
Accept: application/json
Accept-Encoding: gzip
...
2021-02-11T15:29:17.028-0800 [INFO]  plugin.terraform-provider-equinix: 2021/02/11 15:29:17 [DEBUG] Equinix API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Date: Thu, 11 Feb 2021 23:29:17 GMT
...
X-Application-Context: Equinix Cloud Exchange Fabric

{
 "isFirstPage": false,
 "totalCount": 234,
 "isLastPage": true,
 "pageSize": 100,
 "content": [
...
 ],
 "pageNumber": 2
}
```

### Expected Behavior

Querying for a seller profile that's available in the API would return it from the data source.

### Actual Behavior

It appears there is regression in the master branch code that pulls seller profiles (or there are more profiles now that forces pagination). 

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by mikouaj** [comment]
@eugeniy thanks for rising that issue. Indeed it was pagination related bug that appeared after recent changes in API structs. Issue was fixed by change in `rest-go` repo, corresponding unit test was updated as well.

In general this feature is also covered by `TestAccECXL2SellerProfile` acceptance test, but it was not fully executed after recent changes due to env issues. Test passes now.
