### ISSUE TITLE
Incorrect Azure seller data example in the equinix_ecx_l2_connection documentation

### ISSUE THREAD

**Issue by PiotrAviatrix** [equinix/terraform-provider-equinix#42]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

Azure seller profile name has been changed from "Azure Express Route" to "Azure ExpressRoute". Documentation pages show the original version. 
A data source that returning multiple profiles (#40) would be very handy. Took me quite a while to figure out why the data source started failing all of the sudden.

### Affected Resource(s)

data.equinix_ecx_l2_sellerprofile

**Comment by mikouaj** [comment]
@PiotrAviatrix thank you for rising that issue. 
Data source resulting in list of profiles (#40) will be available in release v1.1 this month.
I will update relevant example as well, many thanks.
In a meantime we are working internally to find better way to unique identify service profiles (i.e. CSP profiles).

**Comment by mikouaj** [comment]
Closing as documentation was updated and #40 implemented.
