### ISSUE TITLE
datasource equinix_fabric_cloud_router uuid must be required

### ISSUE THREAD

**Issue by ocobles** [equinix/terraform-provider-equinix#423]
https://github.com/equinix/terraform-provider-equinix/blob/ca31c98ecd90e808adc170a210bcc0de1cff59ae/equinix/fabric_cloud_router_read_schema.go#L19

**Comment by displague** [comment]
Agreed - the one place where this schema is use requires the user to supply this field as a datasource argument.

https://github.com/equinix/terraform-provider-equinix/blob/main/equinix/data_source_fabric_cloud_router.go#L18-L22

**Comment by thogarty** [comment]
Fixed in version 1.27.0 of Terraform Provider: https://registry.terraform.io/providers/equinix/equinix/1.27.0/docs/data-sources/equinix_fabric_cloud_router

Closing issue.
