### ISSUE TITLE
[Bug]: e2e TestAccMetalOrganization_create error 500

### ISSUE THREAD

**Issue by ocobles** [equinix/terraform-provider-equinix#463]
TestAccMetalOrganization_create test is been failing for a while, I haven't identified when it last worked fine

https://github.com/equinix/terraform-provider-equinix/actions/runs/6829925647/job/18577020590#step:5:423

**Comment by ctreatma** [comment]
Worth noting that there is also a[ test helper in metal-cli ](https://github.com/equinix/metal-cli/blob/4557cff2ae313fdecfe5ea4d0c0d8e8243cb686a/test/helper/helper.go#L367)that creates an organization, and the [test that uses that helper](https://github.com/equinix/metal-cli/blob/4557cff2ae313fdecfe5ea4d0c0d8e8243cb686a/test/e2e/projecttest/project_test.go#L44) passes, so digging into the difference between what that test helper does and what the organization resource does may help us fix this test failure.
