### ISSUE TITLE
[Bug]: Cannot set metro to any or a list of metros

### ISSUE THREAD

**Issue by eifrach** [equinix/terraform-provider-equinix#503]
### Terraform Version

Terraform v1.6.6  linux_amd64

### Equinix Provider Version

v1.22.0

### Effected Terraform Resources

 "equinix_metal_device"  

### Terraform Config Files

```
resource "equinix_metal_device" "ci_devices" {
  for_each = { for idx, device in var.devices : idx => device }

  hostname         = each.value["hostname"]
  plan             = each.value["plan"]
  metro            = each.value["metros"]   #  metros  = optional(string, null)
  operating_system = each.value["operating_system"]
  project_id       = each.value["project_id"]
  tags             = each.value["tags"]

```

### Panic Output

```
│ Error: API Error HTTP 422 value.metros is not a valid metro
│                                                                                                
│   with equinix_metal_device.ci_devices["0"],  
│   on main.tf line 9, in resource "equinix_metal_device" "ci_devices":
│    9: resource "equinix_metal_device" "ci_devices" {

```

### Expected Behavior

allow either `null` value or "" 

### Actual Behavior

failed

### Steps to Reproduce

try to create resource with `metro = ""` or with outmetro

**Comment by ctreatma** [comment]
Equinix Metal does not currently support deploying to multiple metros via a list or deploying to an arbitrary metro with `any`.

There is a feature request to add platform support for arbitrary or multiple metros here: https://feedback.equinixmetal.com/instances/p/provide-more-metro-location-options-when-provisioning-instances

In terraform, you could _approximate_ these features using existing functionality as follows:

- **Deploying to multiple metros:** Loop over a list of metros to create multiple, separate `equinix_metal_device` resources using the same resource configuration:

```hcl
locals {
  metros = ["sv", "da", "ny"]
}

resource "equinix_metal_device" "example" {
  for_each = { for idx, metro in local.metros: idx => metro }

  # ... other resource config
  metro = metro
}
```

  The above is generalized; in your example you already have a `for_each` in place for `var.devices`, so you could refer to this article for a way to loop over metros and devices without having to flatten the input data yourself: https://www.daveperrett.com/articles/2021/08/19/nested-for-each-with-terraform/

2.  **Deploying to an arbitrary metro:** use the [`equinix_metal_plans`](https://registry.terraform.io/providers/equinix/equinix/latest/docs/data-sources/equinix_metal_plans) data source to look up metros that have capacity for the desired plan and randomly choose one for deployment

```hcl

data "equinix_metal_plans" "example" {
    sort {
        attribute = "pricing_hour"
        direction = "asc"
    }
    filter {
        attribute = "name"
        values    = [var.plan] # Assuming a single desired plan passed as input variable for this example
    }
}

resource "random_integer" "example" {
  min = 0
  max = length(data.equinix_metal_plans.example.available_in_metros)
}


resource "equinix_metal_device" "example" {
   # ... other resource config
  metro = data.equinix_metal_plans.example.available_in_metros[random_integer.example.result]

  lifecycle {
    ignore_changes = [
        metro, # NOTE: you may need to ignore changes to the metro property to avoid accidentally redeploying existing devices due to changes in metro capacity
    ]
  }
}
```

Keep in mind that these are approximations, so they may not match the desired behavior of the actual features if they were implemented in the platform.

**Comment by eifrach** [comment]
thanks fot the quick replay, I was think about doing it this way.
but, when you use the data source you want also to validate the `capacity` for the needed `plan`

when I was testing it, seems  to fail and stop if one of the `metro` doesn't have the required `capacity` 

can we have a ignore / not fail on data source check flag?

**Comment by ctreatma** [comment]
Support for `metro: any` was recently added in the Metal API, although there are some potential issues with using it in terraform.  Those issues (and some updated workarounds) are noted in #624
