### ISSUE TITLE
[Bug]: equinix_fabric_connection project_id to null value

### ISSUE THREAD

**Issue by ndaa-skydance-animation-madrid** [equinix/terraform-provider-equinix#514]
### Terraform Version

terraform cloud 1.5.5

### Equinix Provider Version

version = "1.22.0"

### Effected Terraform Resources

equinix_fabric_connection.project.project_id

### Expected Behavior

After the creation of an equinix_fabric_connection resource, if you run a "terraform plan" or "terraform refresh", should not try to set the project_id to null, this causes changes in every single plan/refresh run.
If I make an API call to /fabric/v4/connections/{connectionID} it return the full info of the connector, project_id included 

### Actual Behavior

With a terraform plan or terraform refresh, the project_id of the existent objects tries to be set in the state as "null"
```Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # equinix_fabric_connection.tertiary will be updated in-place
  ~ resource "equinix_fabric_connection" "tertiary" {
        id              = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
        name            = "FastConnect-Madrid-Ter"
        # (10 unchanged attributes hidden)

      - project {
          - project_id = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX" -> null
        }

        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.```

### Steps to Reproduce

1 - create an equinix_fabric_connection resource
2 - run a terraform plan after the first apply to create the resource

**Comment by displague** [comment]
@ndaa-skydance-animation-madrid thanks for opening the detailed issue. From your description and plan output, it looks like this is more of an annoyance and inaccurate handling of TF state rather than a workload impacting bug. Is that a fair assessment?

We'll look into this. TF state should match API state without unnecessary jitter. 

I would advise against referencing the `equinix_fabric_connection.foo.project.project_id` attribute in other resources based in the meanwhile.

**Comment by ndaa-skydance-animation-madrid** [comment]
Hi @displague that's right and thank you for your work  : )

**Comment by thogarty** [comment]
Hi @ndaa-skydance-animation-madrid , we have an open PR to fix the issue: https://github.com/equinix/terraform-provider-equinix/pull/583

The `project` schema had incorrect attribute behavior that was causing it to trigger an update when it was explicitly defined in the config. Including the `Computed: true` behavior along with some conditional logic for when it is set to Terraform State resolves the issue. I will update you with the release version that contains the fix before closing the issue.

Thank you!
