### ISSUE TITLE
Support Tags for aws l2 connection accepter

### ISSUE THREAD

**Issue by wrgeorge1983** [equinix/terraform-provider-equinix#56]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently the AWS Hosted Connection Accepter creates connections in the AWS account without any tags.  Especially since these objects will accrue AWS costs (hosted connection port costs) we need these tagged as we would other AWS resources.   

### New or Affected Resource(s)

* equinix_ecx_l2_connection_accepter

### Potential Terraform Configuration

```tf
resource "equinix_ecx_l2_connection_accepter" "this" {
  connection_id = equinix_ecx_l2_connection.this.id
  tags = {  # or 'provider_tags' or 'aws_tags' or similar
    application = "infrastructure"
    tag_name1 = "value1"
    tag_name2 = "value2"
    ...
  }
}
```

### References

* #0000

**Comment by displague** [comment]
Hi @wrgeorge1983,

I've been looking into the `equinix_ecx_l2_connection_accepter` resource and from what I can tell, this resource should be removed entirely in favor of AWS provider resources that provide the same service.

[aws_dx_connection](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_connection) provides access to tag attributes for the connection configured at AWS

[aws_dx_connection_confirmation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_connection_confirmation) appears to provide the same functionality as the [equinix_ecx_l2_connection_accepter resource](https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/ecx_l2_connection_accepter).

By managing AWS resources within the Equinix Provider, the Equinix provider takes on AWS credential handling concerns. These are entirely unnecessary if AWS resources are used.  Also, importing AWS packages into the provider complicates the Go dependencies of this project.

**Comment by wrgeorge1983** [comment]
That all sounds about right, but it does mean we would need to stitch the two sets of resources together ourselves.  Perhaps that's easy, but I'd recommend putting up some documentation on how to do that.

**Comment by ocobleseqx** [comment]
``> That all sounds about right, but it does mean we would need to stitch the two sets of resources together ourselves. Perhaps that's easy, but I'd recommend putting up some documentation on how to do that.

The resource `equinix_ecx_l2_connection_accepter` has been deprecated and we have updated the example of the aws connection:

https://github.com/equinix/terraform-provider-equinix/blob/bd54e5dd5c5c7c24e52874a84a3b85134a3c7640/examples/connectivity/aws-connection/main.tf#L21-L55

There's no clean way now to retrieve the `aws_connection_id` value from the upstream Equinix API using terraform, but it can be handle this way using that local variable inlcuded above. Alternatively, you can use the AWS provider dx_connection datasource https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/dx_connection#example-usage including an explicit dependency to the `equinix_ecx_l2_connection` resource:

```
resource "equinix_ecx_l2_connection" "example" {
  name              = "tf-aws-dot1q"
  profile_uuid      = data.equinix_ecx_l2_sellerprofile.aws.uuid
  speed             = 50
  speed_unit        = "MB"
  notifications     = ["example@equinix.com"]
  port_uuid         = data.equinix_ecx_port.dot1q-pri.uuid
  vlan_stag         = 1010
  seller_region     = var.aws_region
  seller_metro_code = var.aws_metro_code
  authorization_key = var.aws_account_id
}

data "aws_dx_connection" "example" {
  name = "tf-aws-dot1q"

  depends_on = [
    equinix_ecx_l2_connection.example,
  ]
}

resource "aws_dx_connection_confirmation" "confirmation" {
  connection_id = data.aws_dx_connection.example.id
}
```
