### ISSUE TITLE
[Bug]: 100G equinix_metal_connection not supported

### ISSUE THREAD

**Issue by lennardk** [equinix/terraform-provider-equinix#595]
### Terraform Version

Terraform v1.5.7

### Equinix Provider Version

version = "1.11.1"

### Effected Terraform Resources

equinix_metal_connection

### Terraform Config Files

data "equinix_metal_connection" interconnections {
    for_each      = var.virtual_circuits
    connection_id = each.value.connection_id
}

### Expected Behavior

100G ports are discovered for use

### Actual Behavior

`Error: 100000000000 is not allowed speed value. Allowed values: [50000000 200000000 500000000 1000000000 2000000000 5000000000 10000000000]`

### Steps to Reproduce

Order a 100G port
Try to use it it

There's no 'additional description' field so I'll just drop it here: probably just needs to be added to https://github.com/equinix/terraform-provider-equinix/blob/main/internal/resources/metal/connection/speed.go?

**Comment by displague** [comment]
100G is documented as a dedicated port speed at https://deploy.equinix.com/product/interconnection/

**Comment by ctreatma** [comment]
Support for arbitrary connection speeds in the `equinix_metal_connection` resource was added in v1.32.0.
