### ISSUE TITLE
[Bug]: data.aws_dx_connection.example.vlan_id under vif resource doesn't work

### ISSUE THREAD

**Issue by ctang10x** [equinix/terraform-provider-equinix#602]
### Terraform Version

TF Cloud

### Equinix Provider Version

version = "~> 3.0"

### Effected Terraform Resources

equinix_fabric_connection

### Terraform Config Files

module "equinix-aws-connection-example" {
  source = "equinix/fabric/equinix//modules/port-connection"

  connection_name             = var.connection_name_eqx1dx1
  connection_type             = var.connection_type
  notifications_type          = var.notifications_type
  notifications_emails        = var.notifications_emails
  bandwidth                   = var.bandwidth
  purchase_order_number       = var.purchase_order_number
  additional_info             = local.additional_info

  # A-side
  aside_port_name             = var.aside_port_name_eqx1dx1
  aside_vlan_tag              = var.aside_vlan_tag_eqxdx1
  #aside_vlan_inner_tag       = var.aside_vlan_inner_tag

  # Z-side
  zside_ap_type               = var.zside_ap_type
  zside_ap_authentication_key = var.zside_ap_authentication_key
  zside_ap_profile_type       = var.zside_ap_profile_type
  zside_location              = var.zside_location
  zside_seller_region         = var.zside_seller_region
  zside_sp_name               = var.zside_sp_name
}
data "aws_dx_connection" "example-dx-connection" {
  depends_on       = [
    module.equinix-aws-connection-example
  ]
  name             = var.connection_name
}

resource "aws_dx_private_virtual_interface" "example-vif" {
  depends_on       = [
    module.example-dx-connection
  ]

  connection_id    = data.aws_dx_connection.example-dx-connection.id
  name             = "example-vif"
  vlan             = 304
# This doesn't work:
#  vlan             = data.aws_dx_connection.example-dx-connection.vlan_id
#
  address_family   = "ipv4"
  bgp_asn          = var.bgp_asn
  amazon_address   = "<blan>"
  customer_address = "<blah>"
  bgp_auth_key     = var.bgp_auth_key
  dx_gateway_id    = aws_dx_gateway.example-dxgw.id
}

### Debug Output

Error1:
Error: Unsupported attribute
on [dx.tf](http://dx.tf/) line 108, in resource "aws_dx_private_virtual_interface" "example-vif":
  vlan             = data.aws_dx_connection.example-dx-connection.vlan_id
This object has no argument, nested block, or exported attribute named "vlan_id".

### Expected Behavior

I could use the DX connection's VLAN ID in the resource "aws_dx_private_virtual_interface".

### Actual Behavior

Errored out. I had to manually get the VLAN ID from the DX Connection (AWS console) and set the VLAN ID (304) in the code.

### Steps to Reproduce

Create DX gateway, create the module for the fabric to DX connection w/ specifying the data for the DX connection, create the VIF

**Comment by ctreatma** [comment]
From the issue description it sounds like this may be due to using an old version of the AWS provider, rather than a bug in the equinix_fabric_connection resource:

- version = "~> 3.0" is not a valid version constraint for the Equinix provider; we are still on 1.x.x, so this version constraint should fail for the Equinix provider
- the aws_dx_connection data source is defined in the AWS provider, and any attributes for it would be defined there
- the AWS provider added the  vlan_id attribute to the aws_dx_connection datasource in version 4.35.0

Could you update the AWS provider version constraint in your config to ensure that it will install a version >= 4.35.0 and see if that resolves the issue?

**Comment by ctreatma** [comment]
Closing as this seems to be an AWS provider issue rather than an Equinix provider issue.  If the error persists after [ensuring the installed AWS provider version is >= 4.35.0](https://github.com/equinix/terraform-provider-equinix/issues/602#issuecomment-1972243802), please reopen this issue.
