### ISSUE TITLE
Error deleting an Equinix Fabric connection to Equinix Metal service provider - Unexpected state DELETED

### ISSUE THREAD

**Issue by ocobleseqx** [equinix/terraform-provider-equinix#61]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/equinix/equinix v1.1.0
+ provider registry.terraform.io/equinix/metal v3.2.0

### Affected Resource(s)

* equinix_ecx_l2_connection

### Terraform Configuration Files

```tf
resource "equinix_ecx_l2_connection" "this" {
    name              = var.fabric_connection_name
    profile_uuid      = data.equinix_ecx_l2_sellerprofile.this.uuid
    speed             = var.fabric_connection_speed
    speed_unit        = var.fabric_connection_speed_unit
    notifications     = var.fabric_connection_notification_users
    device_uuid       = var.fabric_connection_device_id
    seller_metro_code = var.metal_connection_metro
    authorization_key = metal_connection.this.token

    secondary_connection {
        name        = "${var.fabric_connection_name}-sec"
        device_uuid = var.fabric_secondary_connection_device_id
    }
}
```

### Actual Behavior

The following error is displayed executing terraform destroy:

Error: error waiting for connection (eb566ea0-9618-4205-b9d7-b104d6e90b22) to be removed: unexpected state 'DELETED', wanted target 'PENDING_DELETE, DEPROVISIONED'. last error: %!s(<nil>)

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
### References

* #0000

**Comment by ocobleseqx** [comment]
"DELETED" Should be included as another target state in resourceECXL2ConnectionDelete function

https://github.com/equinix/terraform-provider-equinix/blob/master/equinix/resource_ecx_l2_connection.go#L572

**Comment by displague** [comment]
Deleted is available in: 
https://github.com/equinix/ecx-go/blob/614d5dc23f2940c6f23ef4dd85cef95c3633962d/client.go#L35-L36

I don't know the operational flow of this REST API. Is it safe to presume that the existing target states (deprovisioned, pending delete) should be pending states and the only target state should be DELETED?
