### ISSUE TITLE
[Bug]: Fabric resources do not include Terraform UserAgent in API requests

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-equinix#617]
### Terraform Version

1

### Equinix Provider Version

1

### Effected Terraform Resources

equinix_fabric_\*

### Expected Behavior

API requests to the Fabric APIs include the Terraform SDK version and the fabric-go or equinix-metal-go version.

### Actual Behavior

API requests report that the User-Agent is fabric-go

https://github.com/equinix/terraform-provider-equinix/blob/main/internal/config/config.go#L193-L220

### Steps to Reproduce

Run Terraform on Fabric resources and check the User-Agent HTTP Header captured in API activity metrics or debug output 

Related to #252

**Comment by ctreatma** [comment]
This was fixed in #606
