### ISSUE TITLE
[Bug]: can't create a device with `metro = any`

### ISSUE THREAD

**Issue by ctreatma** [equinix/terraform-provider-equinix#624]
### Terraform Version

Terraform v1.5.7 on darwin_arm64

### Equinix Provider Version

version = "1.32.0"

### Affected Terraform Resources

equinix_metal_device

### Terraform Config Files

```hcl
resource "equinix_metal_device" "test" {
  # ... other device settings
  metro = "any"
}
```

### Expected Behavior

The device should be created successfully, and a subsequent `terraform plan` should not show any changes

### Actual Behavior

The device is created successfully, but `terraform plan` always wants to delete and recreate the device because the config value `any` does not match the actual metro in which the device was deployed (e.g., `sv`)

### Steps to Reproduce

1. Configure an `equinix_metal_device` resource with `metro = "any"`
2. Run `terraform plan` 
3. Run `terraform apply`
4. Run `terraform plan` again and see that the device will be recreated

**Comment by ctreatma** [comment]
Workarounds for using `metro = "any"`:

To avoid deleting and recreating a device created with `metro = "any"`, you can tell terraform to ignore changes to the `metro` attribute:

```hcl
resource "equinix_metal_device" "test" {
  # ... other device settings
  metro = "any"

  lifecycle {
    ignore_changes = ["metro"]
  }
}
```

If you need to reference the actual metro in which the device was created (for example, you want to create the device in any metro and then create a VLAN in the same metro), you can use an `equinix_metal_device` datasource to determine the deployed metro:

```hcl
resource "equinix_metal_device" "test" {
  # ... other device settings
  metro = "any"

  lifecycle {
    ignore_changes = ["metro"]
  }
}

data "equinix_metal_device" "test" {
  id = equinix_metal_device.test.id
}

resource "equinix_metal_vlan" "test" {
  metro = data.equinix_metal_device.test.metro
}
```

**Comment by displague** [comment]
With this, the documentation should be updated to report the behavior change.
