### ISSUE TITLE
[Bug]: equinix_fabric_connection resource parameter causes inconsistent final plan error

### ISSUE THREAD

**Issue by jakubpech** [equinix/terraform-provider-equinix#638]
### Issue description

The parameter "provider_connection_id" `equinix_fabric_connection.resource_name.z_side[*].access_point[*].provider_connection_id` defaults to an empty string during the first TF plan. This causes any resource referencing this value to fail during the apply job because the value changes during the apply run from "" to the actual connection_id value, which is not allowed by Terraform.  

The result is "Error: Provider produced inconsistent final plan".

The parameter "provider_connection_id" should not contain any value until the create function has finished and the actual ID is known. The most of the equinix_fabric_connection parameters work exactly like that, their status is (known after apply) during the first TF plan, but the "provider_connection_id" is assigned an empty string value for some reason.

We can reproduce it 100% time when referencing the provider_connection_id by any other resource (tested with multiple plugins as well as the TF native terraform_data resource). 

The second and any subsequent runs are ok, because the equinix_fabric_connection already exists and contains the correct connection ID already during the plan.

### Terraform Version

v1.5.7

### Equinix Provider Version

1.34.0

### Effected Terraform Resources

equinix_fabric_connection

### Terraform Config Files
```
locals {
  aws_deployment_account = "<account_id>"
  equinix_project_id = "<project_uuid>"
  edge_uuid = "<edge_uuid_for_aws_dx_fabric_connection>"
  edge_interface_id = 4 
}

data "equinix_fabric_service_profiles" "aws" {
  filter {
    property = "/name"
    operator = "="
    values   = ["AWS Direct Connect"]
  }
}

resource "equinix_fabric_connection" "connection_edge_01_ams_to_aws_ams_01" {
  name        = "debug-conn-aws"
  type        = "EVPL_VC"
  bandwidth   = 50
  description = "AWS connection: Amsterdam Edge - Amsterdam AWS"

  notifications {
    type   = "ALL"
    emails = ["xxx@yyy.nl"]
  }

  redundancy {
    priority = "PRIMARY"
  }

  order {
  }

  a_side {
    access_point {
      type = "VD"
      virtual_device {
        type = "EDGE"
        uuid = local.edge_uuid
      }
      interface {
        type = "CLOUD"
        id   = local.edge_interface_id
      }
    }
  }

  z_side {
    access_point {
      type               = "SP"
      authentication_key = local.aws_deployment_account
      seller_region      = "eu-central-1"
      profile {
        type = "L2_PROFILE"
        uuid = data.equinix_fabric_service_profiles.aws.id
      }
      location {
        metro_code = "AM"
      }
    }
  }

  project {
    project_id = local.equinix_project_id
  }
}

# no-action resource to demonstrate that "provider_connection_id" parameter is set to "" already in the plan and changes to "dxcon-12345678" during apply resulting to "Provider produced inconsistent final plan" error.
# the same error occur when "provider_connection_id" is referenced by any other resource, e.g. aws_dx_connection_confirmation resource
resource "terraform_data" "test" {
  input = equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01.z_side[*].access_point[*].provider_connection_id
}

output "aaa" {
  value = terraform_data.test.output
}
```

### Debug Output

```
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Selecting the workspace...
Switched to workspace "fabric_debugging".
equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01: Creating...
equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01: Still creating... [10s elapsed]
equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01: Still creating... [20s elapsed]
equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01: Still creating... [30s elapsed]
equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01: Still creating... [40s elapsed]
equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01: Still creating... [50s elapsed]
equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01: Still creating... [1m0s elapsed]
equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01: Creation complete after 1m8s [id=1653055c-0a62-4caa-b7c9-1feaad74224a]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for terraform_data.test to include new values
│ learned so far during apply, provider "terraform.io/builtin/terraform"
│ produced an invalid new value for .input[0][0]: was cty.StringVal(""), but
│ now cty.StringVal("dxcon-fgniwyp9").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Expected Behavior

The parameter "provider_connection_id" should be **(known after apply)** and not an **empty string** during the first TF plan.

`equinix_fabric_connection.resource_name.z_side[*].access_point[*].provider_connection_id`

The parameter "provider_connection_id" is required to accept the AWS DirectConnect line via the "aws_dx_connection_confirmation" resource.

```
 resource "aws_dx_connection_confirmation" "approve_dx_line" {
  connection_id = element(one(equinix_fabric_connection.resource_name.z_side[*].access_point[*].provider_connection_id), 0)
}
```

### Actual Behavior

The "equinix_fabric_connection" resource parameter "z_side.access_point.provider_connection_id" has an empty string value already during the first Terraform plan so once the value changes during Terraform apply to the actual value of the AWS DX connection, Terraform returns the error: "Provider produced inconsistent final plan".

This prevents any Terraform resource from referencing the "provider_connection_id" parameter.

This only happens during the first Terraform run. The second run where the connection resource is already created uses the correct value.

### Steps to Reproduce

Deploy AWS DirectConnect `equinix_fabric_connection` and reference it's `z_side[*].access_point[*].provider_connection_id` parameter by any other resource (e.g. by aws_dx_connection_confirmation or by terraform_data null resource to simplify the debug deployment).

**Comment by jakubpech** [comment]
For other customers impacted by this issue:

The workaround for this issue is to use the `aws_dx_connection` data source to get the DirectConnect connection id. Equinix examples recommend this, but unfortunately, it has a very nasty side effect. If you update ANY parameter of the Fabric line (e.g. description, notifications list, etc.), Terraform will destroy and re-create all your AWS resources referencing this data source - like your VIFs with BGP peering, causing 20+ minutes of line outage.

```
# Let's use datasource here because "equinix_fabric_connection" resource doesn't return the DX connection id consistently in the 1st pipeline run
data "aws_dx_connection" "connection_edge_01_ams_to_aws_ams_01" {
  name     = equinix_fabric_connection.connection_edge_01_ams_to_aws_ams_01.name
}

# Accept AWS connection: Amsterdam Edge - Amsterdam AWS
resource "aws_dx_connection_confirmation" "approve_edge_01_ams_to_aws_ams_01" {
  connection_id = data.aws_dx_connection.connection_edge_01_ams_to_aws_ams_01.id
}
```

**Comment by thogarty** [comment]
Resolved with this PR: https://github.com/equinix/terraform-provider-equinix/pull/646

Schema behavior for `provider_connection_id` just needed to be marked as `computed` to allow it to be set into state at the appropriate time. Marking issued closed.

**Comment by grotewortel** [comment]
We can confirm this was solved.
Thank you.
