### ISSUE TITLE
unsupported state format version: expected "0.1", got "0.2" error running acceptance test

### ISSUE THREAD

**Issue by ocobleseqx** [equinix/terraform-provider-equinix#72]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

```
$ terraform version
Terraform v1.0.11
on linux_amd64
$ go version
go version go1.17.3 linux/amd64
```

### Expected Behavior

Acceptance tests run without failures

### Actual Behavior

````
=== CONT  TestAccFabricPort
    data_source_ecx_port_acc_test.go:20: Step 1/1 error: unsupported state format version: expected "0.1", got "0.2"
    testing_new.go:56: Error retrieving state, there may be dangling resources: unsupported state format version: expected "0.1", got "0.2"
--- FAIL: TestAccFabricPort (1.08s)
=== CONT  TestAccECXL2SellerProfiles
    data_source_ecx_l2_sellerprofiles_acc_test.go:22: Step 1/1 error: unsupported state format version: expected "0.1", got "0.2"
    testing_new.go:56: Error retrieving state, there may be dangling resources: unsupported state format version: expected "0.1", got "0.2"
--- FAIL: TestAccECXL2SellerProfiles (1.20s)
FAIL
FAIL    github.com/equinix/terraform-provider-equinix/equinix   32.012s
FAIL
make: *** [GNUmakefile:18: testacc] Error 1

````
### Steps to Reproduce

1. `make testacc`

### References

* #0000

**Comment by ocobleseqx** [comment]
Apparently fixed in [terraform-plugin-sdk/v2 v2.7.0](https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.9.0/CHANGELOG.md#270-june-25-2021)

**Comment by displague** [comment]
Similar issue on the Metal provider was cured the same way
https://github.com/equinix/terraform-provider-metal/issues/155

**Comment by displague** [comment]
This is working now (you can run `make testacc` without receiving this error).
