### ISSUE TITLE
[Bug]: terraform plan fails for  data resource that allow user to fetch port by name 

### ISSUE THREAD

**Issue by Mithun2507** [equinix/terraform-provider-equinix#802]
### Terraform Version

v1.7.4

### Equinix Provider Version

version = "1.36"

### Effected Terraform Resources

equinix_fabric_ports
https://registry.terraform.io/providers/equinix/equinix/latest/docs/data-sources/fabric_ports

### Terraform Config Files

# data "equinix_fabric_ports" "equinix_port_chicago_1" {
#   filters {
#     name = local.equinix_port_chicago_1
#   }

### Expected Behavior

On terraform plan lookup should run without any error

### Actual Behavior

the terraform plan fails with below error 

Error: json: cannot unmarshal number into Go struct field _AllPortsResponse.data of type string
│ 
│   with data.equinix_fabric_ports.equinix_port_chicago_1,
│   on network.tf line 223, in data "equinix_fabric_ports" "equinix_port_chicago_1":

### Steps to Reproduce

> write the above terraform code
> ensure correct Equinix provider authentication
> run terraform plan
> same error occurs for all Equinix provider versions

**Comment by thogarty** [comment]
Hi @Mithun2507 , this is a known issue which we have fixed with version v2.9.0. Please upgrade your Equinix Terraform Version to resolve the issue.
